export const tarotCards = [
  {
    "name": "The Fool",
    "number": 0,
    "arcana": "Major",
    "suit": null,
    "keywords": ["beginnings", "innocence", "adventure", "spontaneity"],
    "meaning_up": "New beginnings, innocence, a free spirit.",
    "meaning_rev": "Recklessness, fear of the unknown, foolishness.",
    "short_description": "A leap into the unknown. Trust and adventure await.",
    "detailed_description": "The Fool represents the start of a journey, full of boundless potential and optimism. He leaps into the unknown, unaware of the challenges ahead but buoyed by a sense of wonder and trust. This card encourages embracing new opportunities with a spirit of adventure and openness."
  },
  {
    "name": "The Magician",
    "number": 1,
    "arcana": "Major",
    "suit": null,
    "keywords": ["manifestation", "power", "resourcefulness", "skill"],
    "meaning_up": "Manifestation, resourcefulness, power, inspired action.",
    "meaning_rev": "Manipulation, poor planning, untapped talents.",
    "short_description": "Harness your resources. Turn ideas into reality.",
    "detailed_description": "The Magician symbolizes skill, mastery, and the ability to bring dreams into reality. He channels energy from above to below, commanding all elements at his disposal. This card urges you to use your talents, focus your will, and act confidently to achieve your goals."
  },
  {
    "name": "The High Priestess",
    "number": 2,
    "arcana": "Major",
    "suit": null,
    "keywords": ["intuition", "mystery", "subconscious", "wisdom"],
    "meaning_up": "Intuition, unconscious knowledge, divine feminine.",
    "meaning_rev": "Secrets, disconnected from intuition, hidden agendas.",
    "short_description": "Listen to the quiet voice within. Trust your inner wisdom.",
    "detailed_description": "The High Priestess sits at the threshold of the seen and unseen worlds. She invites you to look beyond the obvious and trust the deep knowledge of your subconscious mind. Mystery and spiritual insight are at play; patience and quiet reflection are your allies."
  },
  {
    "name": "The Empress",
    "number": 3,
    "arcana": "Major",
    "suit": null,
    "keywords": ["fertility", "abundance", "nurture", "beauty"],
    "meaning_up": "Fertility, abundance, nurturing energy.",
    "meaning_rev": "Dependence on others, creative block, smothering.",
    "short_description": "Creation blooms. Embrace abundance and nurture.",
    "detailed_description": "The Empress embodies growth, fertility, and the nurturing power of nature. She signals a time of creativity, beauty, and abundance. Whether it's relationships, projects, or personal development, the seeds you plant now will flourish under her care and attention."
  },
  {
    "name": "The Emperor",
    "number": 4,
    "arcana": "Major",
    "suit": null,
    "keywords": ["authority", "structure", "control", "fatherhood"],
    "meaning_up": "Authority, stability, structure, leadership.",
    "meaning_rev": "Tyranny, rigidity, domination, lack of discipline.",
    "short_description": "Set strong foundations. Lead with wisdom and strength.",
    "detailed_description": "The Emperor represents control, stability, and the rule of law. He brings order to chaos and protects what is built. This card calls for a firm but fair leadership style, clear boundaries, and unwavering commitment to your responsibilities."
  },
  {
    "name": "The Hierophant",
    "number": 5,
    "arcana": "Major",
    "suit": null,
    "keywords": ["tradition", "spiritual wisdom", "conformity", "beliefs"],
    "meaning_up": "Spiritual guidance, tradition, conformity, institutions.",
    "meaning_rev": "Rebellion, subversiveness, new approaches.",
    "short_description": "Seek wisdom through tradition or community.",
    "detailed_description": "The Hierophant stands as a bridge between the divine and humanity, often representing organized belief systems and traditional values. He urges you to seek wisdom through established structures and mentors. Respect for tradition can offer security and grounding in uncertain times."
  },
  {
    "name": "The Lovers",
    "number": 6,
    "arcana": "Major",
    "suit": null,
    "keywords": ["love", "harmony", "partnership", "choices"],
    "meaning_up": "Love, relationships, values alignment, choices.",
    "meaning_rev": "Disharmony, imbalance, misaligned values.",
    "short_description": "Union and choice. Align your heart and mind.",
    "detailed_description": "The Lovers card speaks of deep bonds and meaningful choices. Whether in love, friendship, or moral decision-making, it highlights the importance of being true to your values. Honest communication and wholehearted commitment are essential themes."
  },
  {
    "name": "The Chariot",
    "number": 7,
    "arcana": "Major",
    "suit": null,
    "keywords": ["willpower", "control", "victory", "determination"],
    "meaning_up": "Control, willpower, success, determination.",
    "meaning_rev": "Self-doubt, lack of control, aggression.",
    "short_description": "Seize the reins. Victory through focus and discipline.",
    "detailed_description": "The Chariot is a symbol of triumph through determination and self-control. Harnessing opposing forces, the driver maintains a firm grip on his direction. This card encourages unwavering focus, confidence, and balance to achieve your goals despite challenges."
  },
  {
    "name": "Justice",
    "number": 8,
    "arcana": "Major",
    "suit": null,
    "keywords": ["fairness", "truth", "law", "cause and effect"],
    "meaning_up": "Justice, fairness, truth, law and order.",
    "meaning_rev": "Unfairness, dishonesty, lack of accountability.",
    "short_description": "Balance the scales. Seek truth and accountability.",
    "detailed_description": "Justice reminds you that your actions have consequences. It demands truth, fairness, and objective judgment. Whether facing a decision or the results of past behavior, this card insists on personal responsibility and integrity. What you sow, you shall reap."
  },
  {
    "name": "The Hermit",
    "number": 9,
    "arcana": "Major",
    "suit": null,
    "keywords": ["soul-searching", "introspection", "inner guidance", "solitude"],
    "meaning_up": "Inner reflection, solitude, soul-searching, wisdom.",
    "meaning_rev": "Isolation, loneliness, withdrawal, aimlessness.",
    "short_description": "Retreat inward. Find answers in stillness.",
    "detailed_description": "The Hermit represents a journey inward for wisdom and clarity. Sometimes you need to step away from external noise to hear your inner voice. Seek solitude, trust your intuition, and reconnect with your deeper purpose. Guidance is found within, not without."
  },
  {
    "name": "Wheel of Fortune",
    "number": 10,
    "arcana": "Major",
    "suit": null,
    "keywords": ["fate", "karma", "cycles", "luck"],
    "meaning_up": "Good luck, life cycles, destiny, a turning point.",
    "meaning_rev": "Bad luck, resistance to change, breaking cycles.",
    "short_description": "The wheel turns. Change is inevitable.",
    "detailed_description": "The Wheel of Fortune reminds you that life moves in cycles — highs follow lows, and vice versa. Fate, luck, and divine timing are at play. Embrace change gracefully, and recognize that some forces are beyond your control. Adaptability is your strength."
  },
  {
    "name": "Strength",
    "number": 11,
    "arcana": "Major",
    "suit": null,
    "keywords": ["courage", "compassion", "inner strength", "patience"],
    "meaning_up": "Courage, persuasion, influence, compassion.",
    "meaning_rev": "Self-doubt, weakness, insecurity, raw emotion.",
    "short_description": "True strength comes from compassion and patience.",
    "detailed_description": "Strength is about mastering yourself — taming inner beasts with calm confidence rather than brute force. This card speaks to resilience, kindness, and the quiet power of endurance. Courage isn’t loud; it’s the steady heart in the storm."
  },
  {
    "name": "The Hanged Man",
    "number": 12,
    "arcana": "Major",
    "suit": null,
    "keywords": ["sacrifice", "letting go", "suspension", "new perspective"],
    "meaning_up": "Pause, surrender, letting go, seeing differently.",
    "meaning_rev": "Stalling, resistance, needless sacrifice.",
    "short_description": "Surrender control. Perspective changes everything.",
    "detailed_description": "The Hanged Man invites you to stop struggling and see things from another angle. Sometimes the only way forward is to let go. A period of suspension or sacrifice may feel uncomfortable, but it clears the way for new insights and transformations."
  },
  {
    "name": "Death",
    "number": 13,
    "arcana": "Major",
    "suit": null,
    "keywords": ["endings", "transformation", "transition", "rebirth"],
    "meaning_up": "Endings, transformation, transition, letting go.",
    "meaning_rev": "Resistance to change, fear of new beginnings.",
    "short_description": "Endings clear the way for new beginnings.",
    "detailed_description": "Despite its ominous name, Death symbolizes transformation and rebirth. Something must end for something new to take its place. It calls for courage to let go of what no longer serves you. Embrace the cycle of life, death, and renewal without fear."
  },
  {
    "name": "Temperance",
    "number": 14,
    "arcana": "Major",
    "suit": null,
    "keywords": ["balance", "moderation", "purpose", "patience"],
    "meaning_up": "Balance, moderation, patience, meaning.",
    "meaning_rev": "Imbalance, excess, lack of long-term vision.",
    "short_description": "Blend opposites. Create harmony through patience.",
    "detailed_description": "Temperance is the art of alchemy — blending different elements to create balance and synergy. It encourages moderation, patience, and finding the middle path. Great things come from steady, measured effort rather than rushing or forcing outcomes."
  },
  {
    "name": "The Devil",
    "number": 15,
    "arcana": "Major",
    "suit": null,
    "keywords": ["addiction", "materialism", "bondage", "temptation"],
    "meaning_up": "Addiction, materialism, playfulness with risk, bondage.",
    "meaning_rev": "Breaking free, detachment, reclaiming power.",
    "short_description": "Face your shadows. Break free from unhealthy chains.",
    "detailed_description": "The Devil represents being trapped by materialism, addiction, or destructive habits — but the chains are often self-imposed. Acknowledge your shadow side without fear. This card invites you to recognize unhealthy attachments and free yourself through awareness and conscious choice."
  },
  {
    "name": "The Tower",
    "number": 16,
    "arcana": "Major",
    "suit": null,
    "keywords": ["sudden upheaval", "chaos", "awakening", "destruction"],
    "meaning_up": "Sudden change, chaos, revelation, awakening.",
    "meaning_rev": "Fear of change, resisting necessary endings.",
    "short_description": "Foundations crumble. Liberation through upheaval.",
    "detailed_description": "The Tower strikes when old structures must fall. Though painful and chaotic, it clears the way for true growth. Expect the unexpected. Collapse makes room for stronger, truer foundations. Surrender to the storm; it's shaking you free."
  },
  {
    "name": "The Star",
    "number": 17,
    "arcana": "Major",
    "suit": null,
    "keywords": ["hope", "inspiration", "serenity", "renewal"],
    "meaning_up": "Hope, faith, rejuvenation, inspiration.",
    "meaning_rev": "Despair, discouragement, lost faith.",
    "short_description": "Hope shines bright after the storm.",
    "detailed_description": "The Star is a beacon of hope and healing after turmoil. It offers spiritual renewal, deep peace, and inspiration. Trust that you are on the right path, guided by your inner light. It's a gentle reminder that after every Tower moment, the Star always rises."
  },
  {
    "name": "The Moon",
    "number": 18,
    "arcana": "Major",
    "suit": null,
    "keywords": ["illusion", "intuition", "deception", "dreams"],
    "meaning_up": "Illusion, fear, anxiety, intuition, the subconscious.",
    "meaning_rev": "Clarity, understanding, facing fears.",
    "short_description": "Tread carefully. All is not as it seems.",
    "detailed_description": "The Moon speaks to confusion, dreams, and the unknown. Things are not what they appear to be. Trust your intuition over logic, but beware of illusions and hidden truths. Emotions run deep, and fear can distort reality — proceed with gentle awareness."
  },
  {
    "name": "The Sun",
    "number": 19,
    "arcana": "Major",
    "suit": null,
    "keywords": ["joy", "success", "vitality", "positivity"],
    "meaning_up": "Joy, success, positivity, vitality.",
    "meaning_rev": "Temporary sadness, clouded joy, delays.",
    "short_description": "Joyful success. Everything under the sun flourishes.",
    "detailed_description": "The Sun brings light, clarity, and a surge of optimism. It's a sign that you are thriving and shining brightly. Success, happiness, and growth are assured. Even setbacks are minor under the Sun's warmth — enjoy this period of vibrant energy and open-hearted living."
  },
  {
    "name": "Judgment",
    "number": 20,
    "arcana": "Major",
    "suit": null,
    "keywords": ["rebirth", "inner calling", "absolution", "awakening"],
    "meaning_up": "Judgment, rebirth, inner calling, absolution.",
    "meaning_rev": "Self-doubt, ignoring a call, fear of change.",
    "short_description": "Answer the call. Embrace transformation.",
    "detailed_description": "Judgment calls you to a higher level of consciousness. It's about answering your soul's call and releasing past guilt. You are being asked to awaken, forgive, and step into a new phase of existence with clarity and purpose. Rise up."
  },
  {
    "name": "The World",
    "number": 21,
    "arcana": "Major",
    "suit": null,
    "keywords": ["completion", "accomplishment", "integration", "wholeness"],
    "meaning_up": "Completion, integration, travel, fulfillment.",
    "meaning_rev": "Shortcuts, delays, incomplete goals.",
    "short_description": "You have arrived. Celebrate your wholeness.",
    "detailed_description": "The World marks the completion of a major journey or cycle. Everything has come full circle, and you are now in a place of mastery and unity. It's a moment of profound achievement and spiritual fulfillment. Celebrate — you've earned it."
  },
  {
    "name": "Ace of Wands",
    "number": 1,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["new beginnings", "inspiration", "creation", "potential"],
    "meaning_up": "Inspiration, new opportunities, growth, potential.",
    "meaning_rev": "Delays, lack of direction, missed opportunities.",
    "short_description": "A fiery spark. A bold new beginning.",
    "detailed_description": "The Ace of Wands is the raw energy of creation and passion. It's the cosmic 'green light' urging you to act on your ideas. This card is about seizing opportunity with both hands and trusting the fire within you to guide you forward."
  },
  {
    "name": "Two of Wands",
    "number": 2,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["planning", "progress", "discovery", "decisions"],
    "meaning_up": "Planning, future decisions, exploration, expansion.",
    "meaning_rev": "Fear of change, playing it safe, bad planning.",
    "short_description": "You’ve got the world in your hands. Now what?",
    "detailed_description": "The Two of Wands asks you to look beyond your comfort zone. You're standing at the threshold, needing to make choices about your future. It’s a card of vision and bold plans — the world is yours, but you have to reach for it."
  },
  {
    "name": "Three of Wands",
    "number": 3,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["expansion", "growth", "foresight", "momentum"],
    "meaning_up": "Expansion, progress, foresight, overseas opportunities.",
    "meaning_rev": "Delays, obstacles to success, poor foresight.",
    "short_description": "Your ships are coming in. Stay the course.",
    "detailed_description": "The Three of Wands represents the payoff after the planning stage. Momentum builds as your ventures start bearing fruit. Keep your vision strong and your patience steady — great things are unfolding just beyond the horizon."
  },
  {
    "name": "Four of Wands",
    "number": 4,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["celebration", "harmony", "homecoming", "stability"],
    "meaning_up": "Celebration, stability, home, community, milestones.",
    "meaning_rev": "Lack of support, instability, incomplete projects.",
    "short_description": "Celebrate good times. Welcome stability.",
    "detailed_description": "The Four of Wands marks joyful milestones: weddings, reunions, achievements. It’s the 'let's throw a party' card. This energy brings a sense of belonging and security — a reminder to savor life's victories, big or small."
  },
  {
    "name": "Five of Wands",
    "number": 5,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["conflict", "competition", "tension", "struggle"],
    "meaning_up": "Competition, tension, conflict, disagreements.",
    "meaning_rev": "Avoiding conflict, inner struggles, compromise.",
    "short_description": "Prepare for some scrappy chaos.",
    "detailed_description": "The Five of Wands throws you into the mix — competition, arguments, or just plain chaos. It’s not necessarily hostile; sometimes conflict fuels growth. Approach tensions with flexibility and humor rather than stubbornness."
  },
  {
    "name": "Six of Wands",
    "number": 6,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["victory", "recognition", "success", "public reward"],
    "meaning_up": "Victory, success, recognition, praise.",
    "meaning_rev": "Pride before a fall, lack of recognition, fall from grace.",
    "short_description": "Ride high. You’ve earned your moment in the sun.",
    "detailed_description": "The Six of Wands is your victory lap. After struggles and setbacks, your efforts are being recognized. Success is here — enjoy it, but remember: true leadership lies in humility and gratitude, not arrogance."
  },
  {
    "name": "Seven of Wands",
    "number": 7,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["challenge", "defense", "perseverance", "standing ground"],
    "meaning_up": "Challenge, competition, protection, perseverance.",
    "meaning_rev": "Overwhelm, giving up, defensiveness.",
    "short_description": "Hold your ground. You’re stronger than you know.",
    "detailed_description": "The Seven of Wands calls for courage. You've earned your place, but now you must defend it. Expect challenges, but don’t back down. This card reminds you that maintaining success often demands just as much strength as reaching it."
  },
  {
    "name": "Eight of Wands",
    "number": 8,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["speed", "movement", "action", "swift change"],
    "meaning_up": "Swift action, progress, quick developments.",
    "meaning_rev": "Delays, frustration, resisting change.",
    "short_description": "Buckle up — things are moving fast.",
    "detailed_description": "The Eight of Wands signals a surge of momentum. Events are picking up speed, communications are flying, and obstacles are falling away. Stay flexible and ready to act. Blink and you might miss your moment — this is the sprint after the marathon."
  },
  {
    "name": "Nine of Wands",
    "number": 9,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["resilience", "perseverance", "defense", "persistence"],
    "meaning_up": "Resilience, persistence, test of faith, boundaries.",
    "meaning_rev": "Exhaustion, defensiveness, paranoia.",
    "short_description": "Wounded but unbroken. Keep going.",
    "detailed_description": "The Nine of Wands is the warrior’s card. You’re battered, bruised, and damn tired — but you’re still standing. Protect what you’ve built, stay alert, and push through. Victory is closer than you think; don't let fatigue steal it from you."
  },
  {
    "name": "Ten of Wands",
    "number": 10,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["burden", "responsibility", "hardship", "stress"],
    "meaning_up": "Burden, extra responsibility, hard work, stress.",
    "meaning_rev": "Avoiding responsibilities, burnout, taking on too much.",
    "short_description": "Carrying the load? Time to lighten it.",
    "detailed_description": "The Ten of Wands shows the weight of success. You’ve achieved much, but at a cost. If you're overwhelmed by duties and stress, it’s time to prioritize or delegate. Not all burdens are yours to carry. Drop what no longer serves you."
  },
  {
    "name": "Page of Wands",
    "number": 11,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["exploration", "enthusiasm", "discovery", "adventure"],
    "meaning_up": "Inspiration, discovery, free spirit, adventure.",
    "meaning_rev": "Haste, setbacks, lack of direction.",
    "short_description": "The world is your playground. Explore it.",
    "detailed_description": "The Page of Wands is the spirited adventurer, eager and wide-eyed. This card invites you to embrace your curiosity, take risks, and follow creative impulses. It's about learning by doing — even if you stumble, you're on the right track."
  },
  {
    "name": "Knight of Wands",
    "number": 12,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["energy", "passion", "adventure", "impulsiveness"],
    "meaning_up": "Energy, passion, inspired action, adventure.",
    "meaning_rev": "Recklessness, haste, anger, frustration.",
    "short_description": "Charge forward — but watch for cliffs.",
    "detailed_description": "The Knight of Wands burns hot and moves fast. This is fearless, action-oriented energy. Great for initiating projects or chasing dreams, but beware of impatience and recklessness. Think 'bold,' not 'brainless.' Harness your passion with purpose."
  },
  {
    "name": "Queen of Wands",
    "number": 13,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["confidence", "independence", "courage", "determination"],
    "meaning_up": "Confidence, courage, determination, joy.",
    "meaning_rev": "Insecurity, jealousy, selfishness.",
    "short_description": "Radiate power. Command respect.",
    "detailed_description": "The Queen of Wands is magnetic, vibrant, and fiercely confident. She knows her worth and inspires others by simply being herself. This card encourages you to step into your power, own your space, and lead with both strength and warmth."
  },
  {
    "name": "King of Wands",
    "number": 14,
    "arcana": "Minor",
    "suit": "Wands",
    "keywords": ["leadership", "vision", "honor", "entrepreneurship"],
    "meaning_up": "Natural leader, vision, entrepreneurship, honor.",
    "meaning_rev": "Impulsiveness, arrogance, ruthless behavior.",
    "short_description": "Lead boldly. See the bigger picture.",
    "detailed_description": "The King of Wands is the ultimate visionary leader — bold, driven, charismatic. He doesn't just dream; he commands reality to align with his vision. This card urges you to think big, lead with integrity, and take daring but calculated risks."
  },
  {
    "name": "Ace of Cups",
    "number": 1,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["new love", "compassion", "creativity", "emotional beginnings"],
    "meaning_up": "Love, new relationships, compassion, creativity.",
    "meaning_rev": "Emotional loss, blocked creativity, emptiness.",
    "short_description": "A heart wide open. Let love flow in.",
    "detailed_description": "The Ace of Cups overflows with emotion and connection. This card signals a new beginning of the heart — love, friendship, joy, or creative passion. Be open to deep emotional experiences; let them wash over you and refresh your spirit."
  },
  {
    "name": "Two of Cups",
    "number": 2,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["partnership", "love", "harmony", "attraction"],
    "meaning_up": "Unified love, partnership, mutual attraction.",
    "meaning_rev": "Imbalance, broken communication, tension.",
    "short_description": "A soulful connection. Two hearts, one beat.",
    "detailed_description": "The Two of Cups is pure relationship energy. It marks bonds formed through mutual respect, trust, and emotional alignment. Whether romantic or platonic, it's a beautiful sign of partnership blossoming into something deeper."
  },
  {
    "name": "Three of Cups",
    "number": 3,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["celebration", "friendship", "community", "joy"],
    "meaning_up": "Celebration, friendship, creativity, community.",
    "meaning_rev": "Overindulgence, gossip, isolation.",
    "short_description": "Raise a glass. You’re not alone.",
    "detailed_description": "The Three of Cups is all about joy shared with others — community, parties, creative collaboration. It encourages celebrating wins (big or small) with the people who lift you up. Lean into support systems and collective happiness."
  },
  {
    "name": "Four of Cups",
    "number": 4,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["apathy", "contemplation", "disconnection", "boredom"],
    "meaning_up": "Apathy, contemplation, feeling disconnected.",
    "meaning_rev": "Awareness, choosing happiness, new outlook.",
    "short_description": "Wake up. Opportunity is knocking.",
    "detailed_description": "The Four of Cups shows someone lost in their own mind, missing opportunities right under their nose. It’s a call to shake off apathy, re-engage with life, and open yourself up to the gifts being quietly offered to you."
  },
  {
    "name": "Five of Cups",
    "number": 5,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["loss", "grief", "regret", "disappointment"],
    "meaning_up": "Regret, failure, disappointment, pessimism.",
    "meaning_rev": "Acceptance, moving on, forgiveness.",
    "short_description": "Grieve the loss, but don't miss what's left.",
    "detailed_description": "The Five of Cups is grief embodied. Loss is real, and it's okay to mourn. But if you stay focused only on what’s spilled, you’ll miss the two full cups still standing. Healing begins when you shift your gaze from sorrow to hope."
  },
  {
    "name": "Six of Cups",
    "number": 6,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["nostalgia", "childhood", "innocence", "reunion"],
    "meaning_up": "Nostalgia, childhood memories, innocence, joy.",
    "meaning_rev": "Stuck in the past, unrealistic expectations.",
    "short_description": "Memory lane isn’t a dead end.",
    "detailed_description": "The Six of Cups invites you to reconnect with innocence, simplicity, and joy. It may bring old friends, memories, or feelings back into focus. Honor the past, but don’t lose yourself there — bring that sense of wonder into today."
  },
  {
    "name": "Seven of Cups",
    "number": 7,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["choices", "illusion", "wishful thinking", "fantasy"],
    "meaning_up": "Many choices, illusion, temptation, wishful thinking.",
    "meaning_rev": "Clarity, decisive action, facing reality.",
    "short_description": "Too many dreams? Time to choose.",
    "detailed_description": "The Seven of Cups dazzles with possibility — and confusion. Not every shiny thing is worth chasing. Pause, assess, and prioritize. Dreams are powerful, but without clear choices and action, they’ll stay floating just out of reach."
  },
  {
    "name": "Eight of Cups",
    "number": 8,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["abandonment", "withdrawal", "seeking", "moving on"],
    "meaning_up": "Walking away, seeking deeper meaning, letting go.",
    "meaning_rev": "Fear of moving on, stagnation, aimlessness.",
    "short_description": "Leave the empty cups behind.",
    "detailed_description": "The Eight of Cups signals a necessary goodbye. It’s the brave choice to walk away from what’s familiar but unfulfilling. Trust your instincts — the path you seek might be unknown, but it holds far greater rewards than staying stuck."
  },
  {
    "name": "Nine of Cups",
    "number": 9,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["contentment", "satisfaction", "gratitude", "wish fulfillment"],
    "meaning_up": "Contentment, satisfaction, emotional stability, wishes coming true.",
    "meaning_rev": "Greed, dissatisfaction, indulgence.",
    "short_description": "Wish granted. Enjoy it (without getting smug).",
    "detailed_description": "The Nine of Cups is the ‘wish card’ — a moment of deep satisfaction and emotional fulfillment. Relish your wins! Just remember: lasting joy comes from genuine gratitude, not flaunting. Stay humble even when life’s treating you like royalty."
  },
  {
    "name": "Ten of Cups",
    "number": 10,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["harmony", "happiness", "family", "emotional bliss"],
    "meaning_up": "Divine love, blissful relationships, harmony, alignment.",
    "meaning_rev": "Broken relationships, misaligned values, domestic discord.",
    "short_description": "The emotional jackpot: real, lasting joy.",
    "detailed_description": "The Ten of Cups is the ultimate emotional fulfillment: love, family, peace, and harmony all wrapped into one technicolor dream. Whether literal or symbolic, it shows a life rich with connection and shared happiness. It's the ‘happily ever after’ card."
  },
  {
    "name": "Page of Cups",
    "number": 11,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["creative beginnings", "intuitive messages", "curiosity", "new emotions"],
    "meaning_up": "Creative opportunities, intuitive messages, curiosity.",
    "meaning_rev": "Emotional immaturity, creative blocks, insecurity.",
    "short_description": "Dream bigger. Feel deeper.",
    "detailed_description": "The Page of Cups brings fresh emotional energy. Expect surprises — a message of love, an intuitive flash, or a creative spark. Stay open-hearted and curious like a kid again. Trust your feelings; they're trying to lead you somewhere wonderful."
  },
  {
    "name": "Knight of Cups",
    "number": 12,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["romance", "idealism", "charm", "invitation"],
    "meaning_up": "Romance, charm, imagination, beauty.",
    "meaning_rev": "Moodiness, disappointment, unrealistic expectations.",
    "short_description": "The poet rides in. Follow the dream (carefully).",
    "detailed_description": "The Knight of Cups is the hopeless romantic of the tarot. Sweeping gestures, heartfelt messages, dreamy ideals — it’s all here. Pursue your dreams passionately, but keep one foot on the ground so you don’t drown in fantasy."
  },
  {
    "name": "Queen of Cups",
    "number": 13,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["compassion", "calm", "intuitive wisdom", "nurturing"],
    "meaning_up": "Compassionate, caring, emotionally stable, intuitive.",
    "meaning_rev": "Emotional insecurity, co-dependency, hypersensitivity.",
    "short_description": "Feel deeply. Rule wisely.",
    "detailed_description": "The Queen of Cups embodies emotional mastery — deep empathy without drowning in others’ needs. She trusts her intuition and leads with compassion. Be receptive and nurturing, but remember: strong boundaries protect tender hearts."
  },
  {
    "name": "King of Cups",
    "number": 14,
    "arcana": "Minor",
    "suit": "Cups",
    "keywords": ["emotional balance", "control", "diplomacy", "compassion"],
    "meaning_up": "Emotional balance, compassion, diplomacy, wisdom.",
    "meaning_rev": "Emotional manipulation, moodiness, coldness.",
    "short_description": "Lead with heart and mind in harmony.",
    "detailed_description": "The King of Cups sits atop turbulent waters — calm, steady, wise. He balances emotion with intellect, offering kindness without losing control. When emotions run high, be like the King: compassionate but firmly anchored."
  },
  {
    "name": "Ace of Swords",
    "number": 1,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["clarity", "breakthrough", "truth", "new ideas"],
    "meaning_up": "Breakthrough, mental clarity, sharp focus.",
    "meaning_rev": "Confusion, chaos, miscommunication.",
    "short_description": "A flash of truth cuts through the fog.",
    "detailed_description": "The Ace of Swords is a razor-edged idea slicing through doubt. It signals clarity, breakthroughs, and powerful new beginnings fueled by truth. Don't shy away from tough realizations — they're your weapon and your shield."
  },
  {
    "name": "Two of Swords",
    "number": 2,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["indecision", "stalemate", "difficult choices", "avoidance"],
    "meaning_up": "Difficult choices, indecision, stalemate.",
    "meaning_rev": "Lesser of two evils, confusion, no right choice.",
    "short_description": "Stuck? It's time to choose — even if it sucks.",
    "detailed_description": "The Two of Swords shows someone blindfolded at a crossroads. Avoidance won't solve your dilemma; you must make a decision. Trust yourself, even if the options aren't perfect. Courage clears the path."
  },
  {
    "name": "Three of Swords",
    "number": 3,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["heartbreak", "pain", "grief", "betrayal"],
    "meaning_up": "Heartbreak, emotional pain, sorrow, grief.",
    "meaning_rev": "Releasing pain, forgiveness, recovery.",
    "short_description": "Ouch. Healing starts with facing it.",
    "detailed_description": "The Three of Swords is the gut-punch card of the deck. Heartbreak, betrayal, grief — it's raw and it hurts. But facing the pain head-on is the first step to true healing. Feel it, mourn it, then rebuild stronger."
  },
  {
    "name": "Four of Swords",
    "number": 4,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["rest", "recovery", "meditation", "rejuvenation"],
    "meaning_up": "Rest, recovery, meditation, retreat.",
    "meaning_rev": "Burnout, restlessness, forced stagnation.",
    "short_description": "Pause the battle. Heal yourself.",
    "detailed_description": "The Four of Swords is a ceasefire in life's endless battles. You need rest — mentally, physically, emotionally. Take time to recover before charging back into the fray. Stillness isn't weakness; it's strategic survival."
  },
  {
    "name": "Five of Swords",
    "number": 5,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["conflict", "defeat", "self-interest", "tension"],
    "meaning_up": "Conflict, tension, winning at a cost.",
    "meaning_rev": "Resolution, forgiveness, reconciliation.",
    "short_description": "You won... but was it worth it?",
    "detailed_description": "The Five of Swords shows hollow victory. You might be right, but at what cost? Examine whether you're fighting battles that don't need winning. Sometimes walking away preserves more than pride — it preserves peace."
  },
  {
    "name": "Six of Swords",
    "number": 6,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["transition", "moving on", "healing", "journey"],
    "meaning_up": "Transition, moving on, journey toward healing.",
    "meaning_rev": "Resistance to change, unfinished business.",
    "short_description": "Row away from the wreckage.",
    "detailed_description": "The Six of Swords marks a painful but necessary transition. You're leaving behind trouble, moving toward calmer waters. It’s bittersweet, but healing demands distance sometimes. Trust the journey — even if it hurts at first."
  },
  {
    "name": "Seven of Swords",
    "number": 7,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["deception", "strategy", "secrecy", "betrayal"],
    "meaning_up": "Deception, trickery, strategic thinking.",
    "meaning_rev": "Coming clean, being caught, rethinking tactics.",
    "short_description": "Sneaky doesn’t always mean evil.",
    "detailed_description": "The Seven of Swords deals in secrets and strategies. Sometimes you need to move quietly; other times, deceit can come back to bite you. Examine your intentions — are you protecting yourself, or sabotaging trust?"
  },
  {
    "name": "Eight of Swords",
    "number": 8,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["restriction", "trapped", "mental prison", "self-limitation"],
    "meaning_up": "Feeling trapped, mental restriction, self-imposed limitations.",
    "meaning_rev": "Release from restriction, mental clarity, new perspective.",
    "short_description": "The only prison is in your mind.",
    "detailed_description": "The Eight of Swords is all about feeling stuck, but this is a mental trap. The walls are made of your own fears and doubts. Break free by changing your perception — it’s not the world that’s keeping you trapped, it’s your mindset."
  },
  {
    "name": "Nine of Swords",
    "number": 9,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["anxiety", "nightmares", "guilt", "sleepless nights"],
    "meaning_up": "Anxiety, guilt, sleepless nights, fear.",
    "meaning_rev": "Facing fears, finding peace, confronting anxiety.",
    "short_description": "Nightmares aren't as real as they seem.",
    "detailed_description": "The Nine of Swords is a card of mental distress and sleepless nights. Your fears may feel overwhelming, but they often have no real power over you. Confronting your anxieties will lead to clarity — the worst is often imagined."
  },
  {
    "name": "Ten of Swords",
    "number": 10,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["betrayal", "endings", "rock bottom", "defeat"],
    "meaning_up": "Betrayal, painful endings, feeling defeated.",
    "meaning_rev": "Recovery, survival, hope after suffering.",
    "short_description": "The worst is over. Time to rise again.",
    "detailed_description": "The Ten of Swords shows a brutal ending, a final blow, but it’s not the end — it's the start of a new chapter. This painful card signifies a rock-bottom moment, but it’s also the moment you rise from the ashes, stronger than before."
  },
  {
    "name": "Page of Swords",
    "number": 11,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["curiosity", "intelligence", "new ideas", "vigilance"],
    "meaning_up": "Curiosity, intelligence, alertness, learning.",
    "meaning_rev": "Impulsiveness, gossip, immaturity, defensiveness.",
    "short_description": "A sharp mind, always questioning.",
    "detailed_description": "The Page of Swords is a messenger of new ideas and mental energy. This card urges you to stay curious and observe your surroundings. The sword here is not for fighting, but for cutting through the fog of ignorance with sharp intelligence."
  },
  {
    "name": "Knight of Swords",
    "number": 12,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["action", "speed", "determination", "boldness"],
    "meaning_up": "Swift action, determination, urgency.",
    "meaning_rev": "Rash decisions, impulsive actions, hasty conclusions.",
    "short_description": "Charge ahead — but watch your step.",
    "detailed_description": "The Knight of Swords is a force of will, charging forward with relentless speed. While your actions are decisive and bold, be mindful of rushing in too quickly. Sometimes, a little patience goes a long way."
  },
  {
    "name": "Queen of Swords",
    "number": 13,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["perception", "independence", "truth", "clear communication"],
    "meaning_up": "Perception, clarity, independence, truthful communication.",
    "meaning_rev": "Coldness, bitterness, cutting words.",
    "short_description": "Truth without emotion. Speak your mind.",
    "detailed_description": "The Queen of Swords is the embodiment of clear thought and truth. She cuts through illusion with precision and honesty. When she appears, it's time to see things for what they really are and speak your truth, regardless of how it may be received."
  },
  {
    "name": "King of Swords",
    "number": 14,
    "arcana": "Minor",
    "suit": "Swords",
    "keywords": ["intellect", "authority", "truth", "strategy"],
    "meaning_up": "Intellect, clarity, strategy, authority.",
    "meaning_rev": "Abuse of power, ruthless behavior, manipulation.",
    "short_description": "The sharpest mind in the room.",
    "detailed_description": "The King of Swords is a master of strategy, intellect, and authority. This card represents rational thought, clear communication, and unbiased truth. When you need to make an important decision, the King of Swords advises you to think logically and strategically."
  },
  {
    "name": "Ace of Pentacles",
    "number": 1,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["prosperity", "new beginnings", "abundance", "opportunity"],
    "meaning_up": "New financial or career opportunities, material abundance.",
    "meaning_rev": "Missed opportunities, lack of focus, financial instability.",
    "short_description": "The seed of abundance — plant it.",
    "detailed_description": "The Ace of Pentacles is the promise of prosperity and new beginnings. This is a gift from the universe — a financial or career opportunity that has the potential to grow into something substantial. Plant the seed, nurture it, and watch it flourish."
  },
  {
    "name": "Two of Pentacles",
    "number": 2,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["balance", "adaptability", "financial juggling", "prioritization"],
    "meaning_up": "Balancing work and finances, adaptability, time management.",
    "meaning_rev": "Overwhelm, imbalance, financial stress.",
    "short_description": "Juggle it all, but don’t drop the ball.",
    "detailed_description": "The Two of Pentacles is about balance — managing multiple priorities, whether in work, finances, or life. It’s a reminder to stay adaptable and flexible. When things get chaotic, find your rhythm and keep the juggling act going without losing focus."
  },
  {
    "name": "Three of Pentacles",
    "number": 3,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["collaboration", "teamwork", "mastery", "building"],
    "meaning_up": "Teamwork, skill development, collaboration.",
    "meaning_rev": "Lack of teamwork, miscommunication, underachievement.",
    "short_description": "Great things are built together.",
    "detailed_description": "The Three of Pentacles is all about building something significant with others. It’s a card of collaboration and mastery — whether you're working with a team to bring a project to life or honing your skills. Success is a group effort, so trust the process and the people around you."
  },
  {
    "name": "Four of Pentacles",
    "number": 4,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["security", "control", "possessiveness", "materialism"],
    "meaning_up": "Financial stability, security, holding onto what you have.",
    "meaning_rev": "Greed, hoarding, insecurity, lack of freedom.",
    "short_description": "Protect what’s yours, but don’t clutch too tight.",
    "detailed_description": "The Four of Pentacles speaks to holding onto your possessions or financial security. While it’s important to protect your wealth, be wary of becoming too possessive or controlling. True security comes when you’re not afraid to let go of things when necessary."
  },
  {
    "name": "Five of Pentacles",
    "number": 5,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["financial loss", "hardship", "rejection", "poverty"],
    "meaning_up": "Financial struggles, hardship, feeling left out in the cold.",
    "meaning_rev": "Recovery, hope, turning the corner after hardship.",
    "short_description": "Lean times — but help is closer than you think.",
    "detailed_description": "The Five of Pentacles signifies financial or material hardship, perhaps even feeling abandoned or rejected. But there’s hope. Help is closer than you realize, and these difficult times are only temporary. Lean on others for support if necessary — you don't have to face the struggle alone."
  },
  {
    "name": "Six of Pentacles",
    "number": 6,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["generosity", "charity", "giving", "receiving"],
    "meaning_up": "Generosity, charity, giving and receiving in balance.",
    "meaning_rev": "Imbalance in giving and receiving, exploitation.",
    "short_description": "Give freely, but don’t let yourself be taken for granted.",
    "detailed_description": "The Six of Pentacles is about balance in giving and receiving. It’s a reminder that generosity is a two-way street. Whether you’re the giver or the receiver, be mindful of the flow of energy and resources. Generosity should be motivated by kindness, not obligation."
  },
  {
    "name": "Seven of Pentacles",
    "number": 7,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["patience", "evaluation", "long-term growth", "reflection"],
    "meaning_up": "Long-term success, evaluation, patience, re-evaluation of progress.",
    "meaning_rev": "Lack of progress, impatience, unwise investments.",
    "short_description": "Progress takes time. Are you on track?",
    "detailed_description": "The Seven of Pentacles signals a moment of reflection. You’ve put in hard work, but now is the time to step back and evaluate. Is your progress aligned with your goals? Be patient and realistic; long-term success takes time and careful tending."
  },
  {
    "name": "Eight of Pentacles",
    "number": 8,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["mastery", "apprenticeship", "hard work", "attention to detail"],
    "meaning_up": "Diligence, craftsmanship, skill development, hard work.",
    "meaning_rev": "Lack of focus, shortcuts, unskilled work.",
    "short_description": "Work hard, perfect your craft.",
    "detailed_description": "The Eight of Pentacles is the card of mastering your craft. Whether it’s a career, a hobby, or personal growth, it speaks to dedication and hard work. Stay focused on honing your skills, and the rewards will come — don’t rush the process."
  },
  {
    "name": "Nine of Pentacles",
    "number": 9,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["luxury", "self-sufficiency", "independence", "achievement"],
    "meaning_up": "Financial independence, luxury, self-sufficiency, success.",
    "meaning_rev": "Isolation, overindulgence, lack of fulfillment.",
    "short_description": "Enjoy the fruits of your labor, but stay grounded.",
    "detailed_description": "The Nine of Pentacles is a card of well-earned luxury and financial success. You’ve worked hard and now enjoy the rewards. However, be cautious of slipping into excess or isolation. True fulfillment comes from balance — indulge without losing touch with your values."
  },
  {
    "name": "Ten of Pentacles",
    "number": 10,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["wealth", "legacy", "family", "long-term success"],
    "meaning_up": "Generational wealth, family legacy, long-term success, stability.",
    "meaning_rev": "Financial instability, broken family, loss of wealth.",
    "short_description": "Leave a legacy, build generational wealth.",
    "detailed_description": "The Ten of Pentacles represents lasting wealth, family, and long-term success. It’s about building something that lasts — not just for you, but for future generations. Whether it’s financial, familial, or spiritual, what you create today will ripple through time."
  },
  {
    "name": "Page of Pentacles",
    "number": 11,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["ambition", "study", "manifestation", "new opportunities"],
    "meaning_up": "New financial opportunities, ambition, study, manifestation.",
    "meaning_rev": "Lack of focus, immaturity, missed opportunities.",
    "short_description": "Dream big, start small, and learn along the way.",
    "detailed_description": "The Page of Pentacles is a card of ambition and new opportunities. If you're studying, working on a new project, or manifesting new financial goals, this card shows that now is the time to put your ideas into action. Start small, stay dedicated, and watch your efforts pay off."
  },
  {
    "name": "Knight of Pentacles",
    "number": 12,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["hard work", "responsibility", "commitment", "patience"],
    "meaning_up": "Hard work, responsibility, patience, commitment to goals.",
    "meaning_rev": "Laziness, stagnation, lack of progress, irresponsibility.",
    "short_description": "Consistency is key. Keep pushing forward.",
    "detailed_description": "The Knight of Pentacles represents dedication and hard work. There’s no shortcut to success, and this knight knows that. He’s willing to put in the time and effort necessary to achieve his goals. If you’ve been feeling stagnant, it’s time to reignite that sense of responsibility and push forward with diligence."
  },
  {
    "name": "Queen of Pentacles",
    "number": 13,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["nurturing", "practicality", "abundance", "maternal care"],
    "meaning_up": "Nurturing, abundance, practical support, motherly care.",
    "meaning_rev": "Neglect, overindulgence, materialism, codependency.",
    "short_description": "Care for yourself, and abundance will follow.",
    "detailed_description": "The Queen of Pentacles is the embodiment of practical nurturing. She supports and cares for others, but also knows how to create abundance for herself. She reminds you to take care of your body, your finances, and your home. When you nurture yourself, you can more effectively nurture the world around you."
  },
  {
    "name": "King of Pentacles",
    "number": 14,
    "arcana": "Minor",
    "suit": "Pentacles",
    "keywords": ["wealth", "stability", "leadership", "business acumen"],
    "meaning_up": "Wealth, stability, leadership, financial success.",
    "meaning_rev": "Greed, overindulgence, materialism, lack of generosity.",
    "short_description": "Master of wealth and stability. Lead with wisdom.",
    "detailed_description": "The King of Pentacles is the archetype of financial success and stability. He’s built his wealth through hard work, wisdom, and a solid foundation. This card speaks to leadership, business acumen, and the ability to create lasting security. But remember, true wealth isn’t just about material possessions — it’s about using your resources responsibly and with generosity."
  }
]
  
  